- name: Set prompt name
  ansible.builtin.shell: set prompt {{ app_name }}

- name: Disable existing redis version
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable redis version 20
  ansible.builtin.shell: dnf module enable redis:7 -y

- name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Replace hostname in conf file
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Replace the protected mode
  ansible.builtin.lineinfile:
    path: /etc/redis/redis/conf
    regexp: 'protected-mode'
    replace: 'protected-mode no'

- name: Include common role
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: true