- name: Include maven task
  ansible.builtin.include_role:
    name: common
    tasks_from: maven_setup

- name: Install mysql
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load SQL schema
  ansible.builtin.shell: mysql -h {{ lookup('hashi_vault','roboshop-{{env}}/data/shipping:DB_HOST token={{vault_token}} url=http://vault-internal.devops24.shop:8200')}} -u{{ lookup('hashi_vault','roboshop-{{env}}/data/shipping:DB_USER token={{vault_token}} url=http://vault-internal.devops24.shop:8200')}} -p{{ lookup('hashi_vault','roboshop-{{env}}/data/shipping:DB_PASS token={{vault_token}} url=http://vault-internal.devops24.shop:8200')}} < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data

- name: Restart the service
  ansible.builtin.systemd_service:
    name: shipping
    state: restarted