- name: Install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Restart systemctl services
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Setup MySQL Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass "{{ lookup('hashi_vault','roboshop-{{env}}/data/mysql:mysql_root_password token={{vault_token}} url=http://vault-internal.devops24.shop:8200')}}"
