- name: Include nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: load master data
  ansible.builtin.shell: mongosh --host {{ lookup('hashi_vault','roboshop-{{env}}/data/shipping:DB_HOST token={{vault_token}} url=http://vault-internal.devops24.shop:8200')}} </app/{{ lookup('hashi_vault','roboshop-{{env}}/data/catalogue:SCHEMA_FILE token={{vault_token}} url=http://vault-internal.devops24.shop:8200')}}

- name: Restart the systemd service
  ansible.builtin.systemd_service:
    name: catalogue
    state: restarted