- name: Install maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Include pre requisites task
  ansible.builtin.include_tasks:
    file: app_prerequisites

- name: Download application dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{ app_name }}-1.0.jar {{ app_name }}.jar

- name: Include systemd service task
  ansible.builtin.include_tasks:
    file: systemd_setup.yml